Ashley
TLdgh/Data_Analysis_Proj_2 pull request #4
Opened 2023-10-20 02:23 UTC by Aych12

merge

2023-10-20 04:53 UTC, TLdgh requested changes
There was a code chunk that was misplaced and a minor typo, which prevented me from running your file. I corrected it.

Changes need to be made:
1. The Mean Comparison plot from line 146-160 should be written as a general meanplot function in MyClass.
2. The quantile plot from 165-184 should also be written in MyClass. Note it should be a generic function (for example call it IntervalPlot) and it should plot the credible interval and the mean according to what data input I give to it (i.e. old or new).
3. the quantile should not be the quantile of your posterior mean like you've written in line 165. It should be the quantile of your posterior sample! We have the list of posterior samples called posteriors, So you should write a function called calculateCI that calculates the two quantiles for EVERY posterior sample. So in your plot Mean_old Comparison with Confidence Intervals from line 165-184, the band should not be the rectangle, it should be different for every sample size (i.e. every posterior sample).

2023-10-20 07:03 UTC, TLdgh commented
I decided to write the function by myself to save time.

2023-10-21 14:01 UTC, 9242720 approved these changes

2023-10-21 17:46 UTC, TLdgh approved these changes
Codes cleaned up and ready for merge.

2023-10-21 17:47 UTC, merged